/**
 * Seed catalogue: 29 screenshot-derived draft records (mostly BLOCKED/DOCUMENTS_REQUIRED)
 * plus 3 TRIHEX-owned public demo products.
 */

import {
  applyOverride,
  OWNER_AVAILABLE,
  OWNER_ARCHIVE_SLUGS,
  OWNER_BLOCKED_SLUGS,
  OWNER_UNDER_REVIEW,
} from "./catalogue-overrides";
import { sellNprFromUsdt, usdtToUsdMinor } from "./stock-pricing";

export interface SeedVariant {
  sku: string;
  variantName: string;
  durationValue: number | null;
  durationUnit: "DAY" | "WEEK" | "MONTH" | "YEAR" | "CREDITS" | "SESSION" | "ONE_TIME" | null;
  supplierCostUsdMinor: number;
  seedVisibleQuantity: number | null;
  minimumProfitNprMinor?: number;
  /** Manual NPR selling price in minor units (paisa). */
  manualSellingPriceNprMinor?: number;
  /** Original / list package price (NPR minor) — shown struck-through when higher than sell. */
  compareAtPriceNprMinor?: number;
  /** Operational FX: NPR minor units per 1 USD. */
  fxRateNprMinorPerUsd?: number;
  pricingMode?: "MANUAL_ONLY" | "FORMULA_WITH_OVERRIDE" | "FORMULA_ONLY";
  advertisingAllowanceNprMinor?: number;
  paymentAllowanceNprMinor?: number;
  operatingAllowanceNprMinor?: number;
  supportAllowanceNprMinor?: number;
  warrantyAllowanceNprMinor?: number;
  taxAllowanceNprMinor?: number;
  ownerPriceNote?: string;
  purchasable?: boolean;
  adReady?: boolean;
  warrantyValue?: number | null;
  warrantyUnit?: string | null;
  warrantyCoverage?: string | null;
  activationMethod?: string | null;
}

export interface SeedProduct {
  name: string;
  slug: string;
  brandSlug: string;
  categorySlug: string;
  sourceListingText: string;
  shortDescription: string;
  /** Newline-separated plan features (customer-facing). */
  longDescription?: string;
  productType: string;
  fulfillmentType: string;
  productStatus: "DRAFT" | "BLOCKED" | "PUBLIC";
  complianceStatus:
    | "UNREVIEWED"
    | "DOCUMENTS_REQUIRED"
    | "APPROVED"
    | "REJECTED"
    | "SUSPENDED";
  supplyAuthorizationType: string;
  vendorProofStatus: string;
  blockedReason?: string;
  needsDataVerification: boolean;
  featured?: boolean;
  variants: SeedVariant[];
}

export const SEED_CATEGORIES = [
  { name: "AI Tools", slug: "ai-tools", sortOrder: 1 },
  { name: "Design", slug: "design", sortOrder: 2 },
  { name: "Video & Editing", slug: "video-editing", sortOrder: 3 },
  { name: "Developer Tools", slug: "developer-tools", sortOrder: 4 },
  { name: "Learning", slug: "learning", sortOrder: 5 },
  { name: "Productivity", slug: "productivity", sortOrder: 6 },
  { name: "Digital Assets", slug: "digital-assets", sortOrder: 7 },
  { name: "Services", slug: "services", sortOrder: 8 },
] as const;

export const SEED_BRANDS = [
  { name: "Google Gemini", slug: "gemini", isOwnBrand: false },
  { name: "OpenAI", slug: "openai", isOwnBrand: false },
  { name: "Adobe", slug: "adobe", isOwnBrand: false },
  { name: "xAI Grok", slug: "grok", isOwnBrand: false },
  { name: "Coursera", slug: "coursera", isOwnBrand: false },
  { name: "Canva", slug: "canva", isOwnBrand: false },
  { name: "Kling", slug: "kling", isOwnBrand: false },
  { name: "CapCut", slug: "capcut", isOwnBrand: false },
  { name: "Anthropic Claude", slug: "claude", isOwnBrand: false },
  { name: "Cursor", slug: "cursor", isOwnBrand: false },
  { name: "Microsoft", slug: "microsoft", isOwnBrand: false },
  { name: "Grammarly", slug: "grammarly", isOwnBrand: false },
  { name: "NordVPN", slug: "nordvpn", isOwnBrand: false },
  { name: "YouTube", slug: "youtube", isOwnBrand: false },
  { name: "Figma", slug: "figma", isOwnBrand: false },
  { name: "ElevenLabs", slug: "elevenlabs", isOwnBrand: false },
  { name: "Notion", slug: "notion", isOwnBrand: false },
  { name: "TRIHEX DIGITAL", slug: "trihex", isOwnBrand: true },
] as const;

export const SEED_SCREENSHOT_PRODUCTS: SeedProduct[] = [
  {
    name: "Gemini Pro 5 TB — 1 Year",
    slug: "gemini-pro-5tb-1-year",
    brandSlug: "gemini",
    categorySlug: "ai-tools",
    sourceListingText: "Gemini Pro 5 TB — 1 Year Ready Account",
    shortDescription: "Draft listing pending permitted activation method verification.",
    productType: "DIGITAL_LICENSE",
    fulfillmentType: "MANUAL_CUSTOMER_EMAIL_ACTIVATION",
    productStatus: "BLOCKED",
    complianceStatus: "DOCUMENTS_REQUIRED",
    supplyAuthorizationType: "UNKNOWN",
    vendorProofStatus: "NOT_UPLOADED",
    blockedReason: "BLOCKED pending permitted activation method and authorization evidence.",
    needsDataVerification: true,
    variants: [
      {
        sku: "GEM-5TB-1Y-001",
        variantName: "1 Year Ready Account",
        durationValue: 1,
        durationUnit: "YEAR",
        supplierCostUsdMinor: 350,
        seedVisibleQuantity: null,
      },
    ],
  },
  {
    name: "Adobe Creative Cloud — 2 Months",
    slug: "adobe-cc-2-months",
    brandSlug: "adobe",
    categorySlug: "design",
    sourceListingText: "Adobe Creative Cloud — 2 Months",
    shortDescription: "Requires authorized Adobe reseller evidence.",
    productType: "DIGITAL_LICENSE",
    fulfillmentType: "LICENSE_KEY_FROM_AUTHORIZED_DISTRIBUTOR",
    productStatus: "BLOCKED",
    complianceStatus: "DOCUMENTS_REQUIRED",
    supplyAuthorizationType: "UNKNOWN",
    vendorProofStatus: "NOT_UPLOADED",
    blockedReason: "Requires authorized Adobe reseller evidence.",
    needsDataVerification: true,
    variants: [
      {
        sku: "ADB-CC-2M-001",
        variantName: "2 Months",
        durationValue: 2,
        durationUnit: "MONTH",
        supplierCostUsdMinor: 450,
        seedVisibleQuantity: null,
      },
    ],
  },
  {
    name: "SuperGrok — 12 Months",
    slug: "supergrok-12-months",
    brandSlug: "grok",
    categorySlug: "ai-tools",
    sourceListingText: "SuperGrok — 12 Months — FW",
    shortDescription: "Requires official business-seat/reseller evidence.",
    productType: "TEAM_SEAT",
    fulfillmentType: "OFFICIAL_TEAM_INVITATION",
    productStatus: "DRAFT",
    complianceStatus: "DOCUMENTS_REQUIRED",
    supplyAuthorizationType: "UNKNOWN",
    vendorProofStatus: "NOT_UPLOADED",
    needsDataVerification: true,
    variants: [
      {
        sku: "GROK-SG-12M-001",
        variantName: "12 Months FW",
        durationValue: 12,
        durationUnit: "MONTH",
        supplierCostUsdMinor: 4000,
        seedVisibleQuantity: null,
      },
    ],
  },
  {
    name: "Gemini Pro — 18 Months Link",
    slug: "gemini-pro-18-months-link",
    brandSlug: "gemini",
    categorySlug: "ai-tools",
    sourceListingText: "Gemini Pro — 18 Months Link — NW",
    shortDescription: "Blocked until activation and authorization are verified.",
    productType: "DIGITAL_LICENSE",
    fulfillmentType: "MANUAL_CUSTOMER_EMAIL_ACTIVATION",
    productStatus: "BLOCKED",
    complianceStatus: "DOCUMENTS_REQUIRED",
    supplyAuthorizationType: "UNKNOWN",
    vendorProofStatus: "NOT_UPLOADED",
    blockedReason: "BLOCKED until activation method and authorization are verified.",
    needsDataVerification: true,
    variants: [
      {
        sku: "GEM-18M-LNK-001",
        variantName: "18 Months Link NW",
        durationValue: 18,
        durationUnit: "MONTH",
        supplierCostUsdMinor: 300,
        seedVisibleQuantity: null,
        minimumProfitNprMinor: 20000, // NPR 200 target for approved Gemini 18-month
      },
    ],
  },
  {
    name: "Coursera Premium Access — 1 Year",
    slug: "coursera-premium-1-year",
    brandSlug: "coursera",
    categorySlug: "learning",
    sourceListingText: "Coursera Premium Access — 1 Year",
    shortDescription: "Blocked until organization/reseller authorization is verified.",
    productType: "DIGITAL_LICENSE",
    fulfillmentType: "OFFICIAL_TEAM_INVITATION",
    productStatus: "BLOCKED",
    complianceStatus: "DOCUMENTS_REQUIRED",
    supplyAuthorizationType: "UNKNOWN",
    vendorProofStatus: "NOT_UPLOADED",
    blockedReason: "Blocked until organization/reseller authorization is verified.",
    needsDataVerification: true,
    variants: [
      {
        sku: "CRS-PREM-1Y-001",
        variantName: "1 Year",
        durationValue: 1,
        durationUnit: "YEAR",
        supplierCostUsdMinor: 1000,
        seedVisibleQuantity: null,
      },
    ],
  },
  {
    name: "Canva Pro Slot — 1 Year",
    slug: "canva-pro-slot-1-year",
    brandSlug: "canva",
    categorySlug: "design",
    sourceListingText: "Canva Pro Slot — 1 Year",
    shortDescription: "Blocked until authorized reseller/team-seat evidence is verified.",
    productType: "TEAM_SEAT",
    fulfillmentType: "OFFICIAL_TEAM_INVITATION",
    productStatus: "BLOCKED",
    complianceStatus: "DOCUMENTS_REQUIRED",
    supplyAuthorizationType: "UNKNOWN",
    vendorProofStatus: "NOT_UPLOADED",
    blockedReason: "Blocked until authorized reseller/team-seat evidence is verified. Quantity cropped in source.",
    needsDataVerification: true,
    variants: [
      {
        sku: "CNV-SLOT-1Y-001",
        variantName: "1 Year Slot",
        durationValue: 1,
        durationUnit: "YEAR",
        supplierCostUsdMinor: 180,
        seedVisibleQuantity: null,
      },
    ],
  },
  {
    name: "Gemini Pro — 4 Month Link",
    slug: "gemini-pro-4-month-link",
    brandSlug: "gemini",
    categorySlug: "ai-tools",
    sourceListingText: "Gemini Pro — 4 Month Link",
    shortDescription: "Blocked until authorization is verified.",
    productType: "DIGITAL_LICENSE",
    fulfillmentType: "MANUAL_CUSTOMER_EMAIL_ACTIVATION",
    productStatus: "BLOCKED",
    complianceStatus: "DOCUMENTS_REQUIRED",
    supplyAuthorizationType: "UNKNOWN",
    vendorProofStatus: "NOT_UPLOADED",
    blockedReason: "Blocked until authorization is verified.",
    needsDataVerification: true,
    variants: [
      {
        sku: "GEM-4M-LNK-001",
        variantName: "4 Month Link",
        durationValue: 4,
        durationUnit: "MONTH",
        supplierCostUsdMinor: 100,
        seedVisibleQuantity: 8,
      },
    ],
  },
  {
    name: "ChatGPT Plus — 1 Month",
    slug: "chatgpt-plus-1-month-fw",
    brandSlug: "openai",
    categorySlug: "ai-tools",
    sourceListingText: "ChatGPT Plus — 1 Month — Full Warranty",
    shortDescription: "Consumer account product — blocked.",
    productType: "DIGITAL_LICENSE",
    fulfillmentType: "MANUAL_CUSTOMER_EMAIL_ACTIVATION",
    productStatus: "BLOCKED",
    complianceStatus: "REJECTED",
    supplyAuthorizationType: "UNKNOWN",
    vendorProofStatus: "NOT_UPLOADED",
    blockedReason: "ChatGPT consumer accounts are BLOCKED.",
    needsDataVerification: true,
    variants: [
      {
        sku: "GPT-PLUS-1M-FW-001",
        variantName: "1 Month Full Warranty",
        durationValue: 1,
        durationUnit: "MONTH",
        supplierCostUsdMinor: 780,
        seedVisibleQuantity: 11,
      },
    ],
  },
  {
    name: "ChatGPT Plus — 1 Month Gmail",
    slug: "chatgpt-plus-1-month-gmail-w15d",
    brandSlug: "openai",
    categorySlug: "ai-tools",
    sourceListingText: "ChatGPT Plus — 1 Month — Gmail — W15D",
    shortDescription: "Consumer account product — blocked.",
    productType: "DIGITAL_LICENSE",
    fulfillmentType: "MANUAL_CUSTOMER_EMAIL_ACTIVATION",
    productStatus: "BLOCKED",
    complianceStatus: "REJECTED",
    supplyAuthorizationType: "UNKNOWN",
    vendorProofStatus: "NOT_UPLOADED",
    blockedReason: "ChatGPT consumer accounts are BLOCKED.",
    needsDataVerification: true,
    variants: [
      {
        sku: "GPT-PLUS-1M-G15-001",
        variantName: "1 Month Gmail W15D",
        durationValue: 1,
        durationUnit: "MONTH",
        supplierCostUsdMinor: 520,
        seedVisibleQuantity: 8,
      },
    ],
  },
  {
    name: "GPT Plus — Apple Pay Gmail",
    slug: "gpt-plus-apple-pay-gmail-w3d",
    brandSlug: "openai",
    categorySlug: "ai-tools",
    sourceListingText: "GPT Plus — Apple Pay Gmail — W3 Day",
    shortDescription: "Consumer account product — blocked.",
    productType: "DIGITAL_LICENSE",
    fulfillmentType: "MANUAL_CUSTOMER_EMAIL_ACTIVATION",
    productStatus: "BLOCKED",
    complianceStatus: "REJECTED",
    supplyAuthorizationType: "UNKNOWN",
    vendorProofStatus: "NOT_UPLOADED",
    blockedReason: "ChatGPT consumer accounts are BLOCKED.",
    needsDataVerification: true,
    variants: [
      {
        sku: "GPT-PLUS-AP-W3-001",
        variantName: "Apple Pay Gmail W3 Day",
        durationValue: 1,
        durationUnit: "MONTH",
        supplierCostUsdMinor: 312,
        seedVisibleQuantity: 2,
      },
    ],
  },
  {
    name: "Gemini Pro Upgrade Link — 18 Months",
    slug: "gemini-pro-upgrade-link-18-months",
    brandSlug: "gemini",
    categorySlug: "ai-tools",
    sourceListingText: "Gemini Pro Upgrade Link — 18 Months (Vietnamese wording in source)",
    shortDescription: "Blocked until authorization and exact method are verified. Source listing contains Vietnamese wording — not imported as verified claim.",
    productType: "DIGITAL_LICENSE",
    fulfillmentType: "MANUAL_CUSTOMER_EMAIL_ACTIVATION",
    productStatus: "DRAFT",
    complianceStatus: "DOCUMENTS_REQUIRED",
    supplyAuthorizationType: "UNKNOWN",
    vendorProofStatus: "NOT_UPLOADED",
    blockedReason:
      "DRAFT — blocked from public sale until authorization and activation method are verified. Owner price NPR 300 prepared; not purchasable or ad-ready.",
    needsDataVerification: true,
    variants: [
      {
        sku: "GEM-UPG-18M-001",
        variantName: "18 Months Upgrade Link",
        durationValue: 18,
        durationUnit: "MONTH",
        supplierCostUsdMinor: 180,
        seedVisibleQuantity: 70,
        minimumProfitNprMinor: 0,
        // Owner-selected: USD 1.80 × NPR 160 = NPR 288; sell NPR 300 (gross NPR 12)
        fxRateNprMinorPerUsd: 16000,
        manualSellingPriceNprMinor: 30000,
        pricingMode: "MANUAL_ONLY",
        advertisingAllowanceNprMinor: 0,
        paymentAllowanceNprMinor: 0,
        operatingAllowanceNprMinor: 0,
        supportAllowanceNprMinor: 0,
        warrantyAllowanceNprMinor: 0,
        taxAllowanceNprMinor: 0,
        ownerPriceNote: "Owner-selected low launch price",
        purchasable: false,
        adReady: false,
      },
    ],
  },
  {
    name: "Gemini Pro CDK — 12 Months",
    slug: "gemini-pro-cdk-12-months",
    brandSlug: "gemini",
    categorySlug: "ai-tools",
    sourceListingText: "Gemini Pro CDK — 12 Months — description cropped",
    shortDescription: "Verify whether CDK is a legitimate transferable redeem code.",
    productType: "REDEEM_CODE",
    fulfillmentType: "OFFICIAL_REDEEM_CODE",
    productStatus: "DRAFT",
    complianceStatus: "DOCUMENTS_REQUIRED",
    supplyAuthorizationType: "UNKNOWN",
    vendorProofStatus: "NOT_UPLOADED",
    needsDataVerification: true,
    variants: [
      {
        sku: "GEM-CDK-12M-001",
        variantName: "12 Months CDK",
        durationValue: 12,
        durationUnit: "MONTH",
        supplierCostUsdMinor: 180,
        seedVisibleQuantity: 39,
      },
    ],
  },
  {
    name: "Gemini AI Pro 5 TB — 12 Month Mail (A)",
    slug: "gemini-ai-pro-5tb-12m-mail-a",
    brandSlug: "gemini",
    categorySlug: "ai-tools",
    sourceListingText: "Gemini AI Pro 5 TB — 12 Month Mail — description cropped",
    shortDescription: "Blocked until exact fulfillment model is verified.",
    productType: "DIGITAL_LICENSE",
    fulfillmentType: "MANUAL_CUSTOMER_EMAIL_ACTIVATION",
    productStatus: "BLOCKED",
    complianceStatus: "DOCUMENTS_REQUIRED",
    supplyAuthorizationType: "UNKNOWN",
    vendorProofStatus: "NOT_UPLOADED",
    blockedReason: "Blocked until exact fulfillment model is verified. Description cropped.",
    needsDataVerification: true,
    variants: [
      {
        sku: "GEM-5TB-12M-A-001",
        variantName: "12 Month Mail A",
        durationValue: 12,
        durationUnit: "MONTH",
        supplierCostUsdMinor: 468,
        seedVisibleQuantity: 30,
      },
    ],
  },
  {
    name: "Gemini AI Pro 5 TB — 12 Month Mail (B)",
    slug: "gemini-ai-pro-5tb-12m-mail-b",
    brandSlug: "gemini",
    categorySlug: "ai-tools",
    sourceListingText: "Gemini AI Pro 5 TB — 12 Month Mail — second variant, description cropped",
    shortDescription: "Separate from variant A — price and likely warranty differ. Do not merge.",
    productType: "DIGITAL_LICENSE",
    fulfillmentType: "MANUAL_CUSTOMER_EMAIL_ACTIVATION",
    productStatus: "BLOCKED",
    complianceStatus: "DOCUMENTS_REQUIRED",
    supplyAuthorizationType: "UNKNOWN",
    vendorProofStatus: "NOT_UPLOADED",
    blockedReason: "Blocked. Not merged with item 14 because price/warranty likely differ.",
    needsDataVerification: true,
    variants: [
      {
        sku: "GEM-5TB-12M-B-001",
        variantName: "12 Month Mail B",
        durationValue: 12,
        durationUnit: "MONTH",
        supplierCostUsdMinor: 2440,
        seedVisibleQuantity: 2,
      },
    ],
  },
  {
    name: "Grok Super — 1 Year",
    slug: "grok-super-1-year-fww",
    brandSlug: "grok",
    categorySlug: "ai-tools",
    sourceListingText: "Grok Super — 1 Year — FWW",
    shortDescription: "Requires official business-seat/reseller authorization.",
    productType: "TEAM_SEAT",
    fulfillmentType: "OFFICIAL_TEAM_INVITATION",
    productStatus: "DRAFT",
    complianceStatus: "DOCUMENTS_REQUIRED",
    supplyAuthorizationType: "UNKNOWN",
    vendorProofStatus: "NOT_UPLOADED",
    needsDataVerification: true,
    variants: [
      {
        sku: "GROK-SUP-1Y-001",
        variantName: "1 Year FWW",
        durationValue: 1,
        durationUnit: "YEAR",
        supplierCostUsdMinor: 6608,
        seedVisibleQuantity: 6,
      },
    ],
  },
  {
    name: "Grok Super — 3 Months",
    slug: "grok-super-3-months",
    brandSlug: "grok",
    categorySlug: "ai-tools",
    sourceListingText: "Grok Super — 3 Month — Full Warranty",
    shortDescription: "Requires official business-seat/reseller authorization.",
    productType: "TEAM_SEAT",
    fulfillmentType: "OFFICIAL_TEAM_INVITATION",
    productStatus: "DRAFT",
    complianceStatus: "DOCUMENTS_REQUIRED",
    supplyAuthorizationType: "UNKNOWN",
    vendorProofStatus: "NOT_UPLOADED",
    needsDataVerification: true,
    variants: [
      {
        sku: "GROK-SUP-3M-001",
        variantName: "3 Months Full Warranty",
        durationValue: 3,
        durationUnit: "MONTH",
        supplierCostUsdMinor: 1464,
        seedVisibleQuantity: 2,
      },
    ],
  },
  {
    name: "Kling Standard — Credits",
    slug: "kling-standard-680-750-credits",
    brandSlug: "kling",
    categorySlug: "video-editing",
    sourceListingText: "Kling Standard — 680–750 Credits — description cropped",
    shortDescription: "Documents required. Description cropped — verify exact credit amount.",
    productType: "DIGITAL_LICENSE",
    fulfillmentType: "OFFICIAL_REDEEM_CODE",
    productStatus: "DRAFT",
    complianceStatus: "DOCUMENTS_REQUIRED",
    supplyAuthorizationType: "UNKNOWN",
    vendorProofStatus: "NOT_UPLOADED",
    needsDataVerification: true,
    variants: [
      {
        sku: "KLG-STD-CRED-001",
        variantName: "680–750 Credits",
        durationValue: 700,
        durationUnit: "CREDITS",
        supplierCostUsdMinor: 624,
        seedVisibleQuantity: 34,
      },
    ],
  },
  {
    name: "Kling Ultra — 26K Credits",
    slug: "kling-ultra-26k-credits",
    brandSlug: "kling",
    categorySlug: "video-editing",
    sourceListingText: "Kling Ultra — 26K Credits — description cropped",
    shortDescription: "Documents required. Description cropped.",
    productType: "DIGITAL_LICENSE",
    fulfillmentType: "OFFICIAL_REDEEM_CODE",
    productStatus: "DRAFT",
    complianceStatus: "DOCUMENTS_REQUIRED",
    supplyAuthorizationType: "UNKNOWN",
    vendorProofStatus: "NOT_UPLOADED",
    needsDataVerification: true,
    variants: [
      {
        sku: "KLG-ULT-26K-001",
        variantName: "26K Credits",
        durationValue: 26000,
        durationUnit: "CREDITS",
        supplierCostUsdMinor: 7169,
        seedVisibleQuantity: 8,
      },
    ],
  },
  {
    name: "CapCut Pro — 7 Days",
    slug: "capcut-pro-7-days",
    brandSlug: "capcut",
    categorySlug: "video-editing",
    sourceListingText: "CapCut Pro — 7 Days",
    shortDescription: "Documents required for reseller/distribution permissions.",
    productType: "DIGITAL_LICENSE",
    fulfillmentType: "MANUAL_CUSTOMER_EMAIL_ACTIVATION",
    productStatus: "DRAFT",
    complianceStatus: "DOCUMENTS_REQUIRED",
    supplyAuthorizationType: "UNKNOWN",
    vendorProofStatus: "NOT_UPLOADED",
    needsDataVerification: true,
    variants: [
      {
        sku: "CAP-PRO-7D-001",
        variantName: "7 Days",
        durationValue: 7,
        durationUnit: "DAY",
        supplierCostUsdMinor: 69,
        seedVisibleQuantity: 60,
      },
    ],
  },
  {
    name: "CapCut Pro — 30 Days",
    slug: "capcut-pro-30-days",
    brandSlug: "capcut",
    categorySlug: "video-editing",
    sourceListingText: "CapCut Pro — 30 Days — Full Warranty",
    shortDescription: "Documents required. Do not advertise warranty without evidence.",
    productType: "DIGITAL_LICENSE",
    fulfillmentType: "MANUAL_CUSTOMER_EMAIL_ACTIVATION",
    productStatus: "DRAFT",
    complianceStatus: "DOCUMENTS_REQUIRED",
    supplyAuthorizationType: "UNKNOWN",
    vendorProofStatus: "NOT_UPLOADED",
    needsDataVerification: true,
    variants: [
      {
        sku: "CAP-PRO-30D-001",
        variantName: "30 Days",
        durationValue: 30,
        durationUnit: "DAY",
        supplierCostUsdMinor: 300,
        seedVisibleQuantity: 42,
      },
    ],
  },
  {
    name: "CapCut Pro — 6 Months",
    slug: "capcut-pro-6-months",
    brandSlug: "capcut",
    categorySlug: "video-editing",
    sourceListingText: "CapCut Pro — 6 Months — Full Warranty",
    shortDescription: "Documents required for reseller/distribution permissions.",
    productType: "DIGITAL_LICENSE",
    fulfillmentType: "MANUAL_CUSTOMER_EMAIL_ACTIVATION",
    productStatus: "DRAFT",
    complianceStatus: "DOCUMENTS_REQUIRED",
    supplyAuthorizationType: "UNKNOWN",
    vendorProofStatus: "NOT_UPLOADED",
    needsDataVerification: true,
    variants: [
      {
        sku: "CAP-PRO-6M-001",
        variantName: "6 Months",
        durationValue: 6,
        durationUnit: "MONTH",
        supplierCostUsdMinor: 1708,
        seedVisibleQuantity: 30,
      },
    ],
  },
  {
    name: "Canva Pro — 1 Year",
    slug: "canva-pro-1-year",
    brandSlug: "canva",
    categorySlug: "design",
    sourceListingText: "Canva Pro — 1 Year — Full Warranty",
    shortDescription: "Blocked until authorized reseller evidence is verified.",
    productType: "TEAM_SEAT",
    fulfillmentType: "OFFICIAL_TEAM_INVITATION",
    productStatus: "BLOCKED",
    complianceStatus: "DOCUMENTS_REQUIRED",
    supplyAuthorizationType: "UNKNOWN",
    vendorProofStatus: "NOT_UPLOADED",
    blockedReason: "Blocked until authorized reseller evidence is verified.",
    needsDataVerification: true,
    variants: [
      {
        sku: "CNV-PRO-1Y-001",
        variantName: "1 Year",
        durationValue: 1,
        durationUnit: "YEAR",
        supplierCostUsdMinor: 780,
        seedVisibleQuantity: 15,
      },
    ],
  },
  {
    name: "Canva EDU — 1 Year",
    slug: "canva-edu-1-year",
    brandSlug: "canva",
    categorySlug: "design",
    sourceListingText: "Canva EDU — 1 Year — Full Warranty",
    shortDescription: "Education access must not be commercially resold.",
    productType: "DIGITAL_LICENSE",
    fulfillmentType: "MANUAL_CUSTOMER_EMAIL_ACTIVATION",
    productStatus: "BLOCKED",
    complianceStatus: "REJECTED",
    supplyAuthorizationType: "UNKNOWN",
    vendorProofStatus: "NOT_UPLOADED",
    blockedReason: "Canva EDU must never be sold as a commercial consumer product.",
    needsDataVerification: false,
    variants: [
      {
        sku: "CNV-EDU-1Y-001",
        variantName: "1 Year EDU",
        durationValue: 1,
        durationUnit: "YEAR",
        supplierCostUsdMinor: 520,
        seedVisibleQuantity: 11,
      },
    ],
  },
  {
    name: "Claude — x20 w30d",
    slug: "claude-x20-w30d",
    brandSlug: "claude",
    categorySlug: "ai-tools",
    sourceListingText: 'Claude "x20 w30d" — exact product description cropped/unclear',
    shortDescription: "Blocked. Exact product description cropped/unclear.",
    productType: "DIGITAL_LICENSE",
    fulfillmentType: "MANUAL_CUSTOMER_EMAIL_ACTIVATION",
    productStatus: "BLOCKED",
    complianceStatus: "DOCUMENTS_REQUIRED",
    supplyAuthorizationType: "UNKNOWN",
    vendorProofStatus: "NOT_UPLOADED",
    blockedReason: "Exact product description cropped/unclear. Claude consumer defaults BLOCKED.",
    needsDataVerification: true,
    variants: [
      {
        sku: "CLD-X20-W30-001",
        variantName: "x20 w30d",
        durationValue: 30,
        durationUnit: "DAY",
        supplierCostUsdMinor: 12768,
        seedVisibleQuantity: 10,
      },
    ],
  },
  {
    name: "Claude — x5 Personal 30d",
    slug: "claude-x5-personal-30d",
    brandSlug: "claude",
    categorySlug: "ai-tools",
    sourceListingText: 'Claude "x5 personal 30d warranty"',
    shortDescription: "Personal consumer account/access — blocked.",
    productType: "DIGITAL_LICENSE",
    fulfillmentType: "MANUAL_CUSTOMER_EMAIL_ACTIVATION",
    productStatus: "BLOCKED",
    complianceStatus: "REJECTED",
    supplyAuthorizationType: "UNKNOWN",
    vendorProofStatus: "NOT_UPLOADED",
    blockedReason: "Personal consumer account/access must not be sold.",
    needsDataVerification: true,
    variants: [
      {
        sku: "CLD-X5-P30-001",
        variantName: "x5 personal 30d",
        durationValue: 30,
        durationUnit: "DAY",
        supplierCostUsdMinor: 8960,
        seedVisibleQuantity: 6,
      },
    ],
  },
  {
    name: "Cursor Ultra",
    slug: "cursor-ultra",
    brandSlug: "cursor",
    categorySlug: "developer-tools",
    sourceListingText: "Cursor Ultra — Full Warranty",
    shortDescription: "Cursor does not authorize third-party subscription resellers.",
    productType: "DIGITAL_LICENSE",
    fulfillmentType: "MANUAL_CUSTOMER_EMAIL_ACTIVATION",
    productStatus: "BLOCKED",
    complianceStatus: "REJECTED",
    supplyAuthorizationType: "UNKNOWN",
    vendorProofStatus: "NOT_UPLOADED",
    blockedReason: "Cursor does not authorize third-party subscription resellers.",
    needsDataVerification: false,
    variants: [
      {
        sku: "CUR-ULT-001",
        variantName: "Ultra",
        durationValue: 1,
        durationUnit: "MONTH",
        supplierCostUsdMinor: 15681,
        seedVisibleQuantity: 5,
      },
    ],
  },
  {
    name: "Cursor Pro+",
    slug: "cursor-pro-plus",
    brandSlug: "cursor",
    categorySlug: "developer-tools",
    sourceListingText: "Cursor Pro+ — Full Warranty",
    shortDescription: "Cursor does not authorize third-party subscription resellers.",
    productType: "DIGITAL_LICENSE",
    fulfillmentType: "MANUAL_CUSTOMER_EMAIL_ACTIVATION",
    productStatus: "BLOCKED",
    complianceStatus: "REJECTED",
    supplyAuthorizationType: "UNKNOWN",
    vendorProofStatus: "NOT_UPLOADED",
    blockedReason: "Cursor does not authorize third-party subscription resellers.",
    needsDataVerification: false,
    variants: [
      {
        sku: "CUR-PROPLUS-001",
        variantName: "Pro+",
        durationValue: 1,
        durationUnit: "MONTH",
        supplierCostUsdMinor: 5664,
        seedVisibleQuantity: 4,
      },
    ],
  },
  {
    name: "Cursor Pro — 30 Days",
    slug: "cursor-pro-30-days",
    brandSlug: "cursor",
    categorySlug: "developer-tools",
    sourceListingText: "Cursor Pro — 30 Days — Full Warranty",
    shortDescription: "Cursor does not authorize third-party subscription resellers.",
    productType: "DIGITAL_LICENSE",
    fulfillmentType: "MANUAL_CUSTOMER_EMAIL_ACTIVATION",
    productStatus: "BLOCKED",
    complianceStatus: "REJECTED",
    supplyAuthorizationType: "UNKNOWN",
    vendorProofStatus: "NOT_UPLOADED",
    blockedReason: "Cursor does not authorize third-party subscription resellers.",
    needsDataVerification: false,
    variants: [
      {
        sku: "CUR-PRO-30D-001",
        variantName: "Pro 30 Days",
        durationValue: 30,
        durationUnit: "DAY",
        supplierCostUsdMinor: 1806,
        seedVisibleQuantity: 3,
      },
    ],
  },
];

/** TRIHEX-owned products allowed to be PUBLIC when seeded in demo mode */
export const SEED_OWNED_PRODUCTS: SeedProduct[] = [
  {
    name: "AI Prompt Starter Pack",
    slug: "ai-prompt-starter-pack",
    brandSlug: "trihex",
    categorySlug: "digital-assets",
    sourceListingText: "TRIHEX owned — AI Prompt Starter Pack",
    shortDescription:
      "A curated pack of production-ready prompts for creators, students, and freelancers in Nepal.",
    productType: "OWNED_ASSET",
    fulfillmentType: "DOWNLOADABLE_OWNED_ASSET",
    productStatus: "PUBLIC",
    complianceStatus: "APPROVED",
    supplyAuthorizationType: "OWN_DIGITAL_PRODUCT",
    vendorProofStatus: "VERIFIED",
    needsDataVerification: false,
    featured: false,
    variants: [
      {
        sku: "THX-PROMPT-001",
        variantName: "Digital Download",
        durationValue: 1,
        durationUnit: "ONE_TIME",
        supplierCostUsdMinor: 0,
        seedVisibleQuantity: 999,
        manualSellingPriceNprMinor: 29900,
        minimumProfitNprMinor: 29900,
        purchasable: true,
      },
    ],
  },
  {
    name: "Small Business AI Setup",
    slug: "small-business-ai-setup-consultation",
    brandSlug: "trihex",
    categorySlug: "services",
    sourceListingText: "TRIHEX owned — Small Business AI Setup Consultation",
    shortDescription:
      "A 60-minute consultation to map AI tools to your Nepali small-business workflows.",
    productType: "CONSULTATION",
    fulfillmentType: "CONSULTATION",
    productStatus: "PUBLIC",
    complianceStatus: "APPROVED",
    supplyAuthorizationType: "MANAGED_IMPLEMENTATION_SERVICE",
    vendorProofStatus: "VERIFIED",
    needsDataVerification: false,
    featured: false,
    variants: [
      {
        sku: "THX-CONSULT-60-001",
        variantName: "60-Minute Session",
        durationValue: 1,
        durationUnit: "SESSION",
        supplierCostUsdMinor: 0,
        seedVisibleQuantity: 50,
        manualSellingPriceNprMinor: 149900,
        minimumProfitNprMinor: 149900,
        purchasable: true,
      },
    ],
  },
  {
    name: "Workflow Automation Discovery",
    slug: "custom-workflow-automation-discovery",
    brandSlug: "trihex",
    categorySlug: "services",
    sourceListingText: "TRIHEX owned — Custom Workflow Automation Discovery Session",
    shortDescription:
      "Discovery session to design automation for your team tools, forms, and notifications.",
    productType: "CONSULTATION",
    fulfillmentType: "MANAGED_SETUP_SERVICE",
    productStatus: "PUBLIC",
    complianceStatus: "APPROVED",
    supplyAuthorizationType: "MANAGED_IMPLEMENTATION_SERVICE",
    vendorProofStatus: "VERIFIED",
    needsDataVerification: false,
    featured: false,
    variants: [
      {
        sku: "THX-AUTO-DISC-001",
        variantName: "Discovery Session",
        durationValue: 1,
        durationUnit: "SESSION",
        supplierCostUsdMinor: 0,
        seedVisibleQuantity: 30,
        manualSellingPriceNprMinor: 199900,
        minimumProfitNprMinor: 199900,
        purchasable: true,
      },
    ],
  },
];

/** Additional owner-documented packages (under review / OOS until authorized). */
export const SEED_NEW_OWNER_PRODUCTS: SeedProduct[] = [
  {
    name: "Grok Super — 10 Months",
    slug: "grok-super-10-months",
    brandSlug: "grok",
    categorySlug: "ai-tools",
    sourceListingText: "Grok Super — 10 Months",
    shortDescription: "Availability under review pending authorization confirmation.",
    productType: "DIGITAL_LICENSE",
    fulfillmentType: "MANUAL_CUSTOMER_EMAIL_ACTIVATION",
    productStatus: "DRAFT",
    complianceStatus: "DOCUMENTS_REQUIRED",
    supplyAuthorizationType: "UNKNOWN",
    vendorProofStatus: "NOT_UPLOADED",
    needsDataVerification: true,
    variants: [
      {
        sku: "GROK-10M-001",
        variantName: "10 Months",
        durationValue: 10,
        durationUnit: "MONTH",
        supplierCostUsdMinor: 0,
        seedVisibleQuantity: null,
        manualSellingPriceNprMinor: 599900,
        purchasable: false,
      },
    ],
  },
  {
    name: "VEO3 Ultra",
    slug: "veo3-ultra",
    brandSlug: "gemini",
    categorySlug: "video-editing",
    sourceListingText: "VEO3 Ultra",
    shortDescription: "Availability under review pending authorization confirmation.",
    productType: "DIGITAL_LICENSE",
    fulfillmentType: "MANUAL_CUSTOMER_EMAIL_ACTIVATION",
    productStatus: "DRAFT",
    complianceStatus: "DOCUMENTS_REQUIRED",
    supplyAuthorizationType: "UNKNOWN",
    vendorProofStatus: "NOT_UPLOADED",
    needsDataVerification: true,
    variants: [
      {
        sku: "VEO3-ULTRA-001",
        variantName: "VEO3 Ultra",
        durationValue: 1,
        durationUnit: "DAY",
        supplierCostUsdMinor: 0,
        seedVisibleQuantity: null,
        manualSellingPriceNprMinor: 24900,
        purchasable: false,
      },
    ],
  },
  {
    name: "VEO4 Ultra — 25K Credits · 30 Days",
    slug: "veo4-ultra-25k-30-days",
    brandSlug: "gemini",
    categorySlug: "video-editing",
    sourceListingText: "VEO4 Ultra — 25K Credits 30 Days",
    shortDescription: "Currently out of stock.",
    productType: "DIGITAL_LICENSE",
    fulfillmentType: "MANUAL_CUSTOMER_EMAIL_ACTIVATION",
    productStatus: "PUBLIC",
    complianceStatus: "APPROVED",
    supplyAuthorizationType: "UNKNOWN",
    vendorProofStatus: "NOT_UPLOADED",
    needsDataVerification: false,
    variants: [
      {
        sku: "VEO4-25K-30D-001",
        variantName: "25K Credits · 30 Days",
        durationValue: 30,
        durationUnit: "DAY",
        supplierCostUsdMinor: 0,
        seedVisibleQuantity: 0,
        manualSellingPriceNprMinor: 69900,
        purchasable: false,
      },
    ],
  },
  {
    name: "VEO4 Ultra — 25K Credits · Warranty",
    slug: "veo4-ultra-25k-warranty",
    brandSlug: "gemini",
    categorySlug: "video-editing",
    sourceListingText: "VEO4 Ultra — 25K Credits Warranty",
    shortDescription: "Availability under review pending authorization confirmation.",
    productType: "DIGITAL_LICENSE",
    fulfillmentType: "MANUAL_CUSTOMER_EMAIL_ACTIVATION",
    productStatus: "DRAFT",
    complianceStatus: "DOCUMENTS_REQUIRED",
    supplyAuthorizationType: "UNKNOWN",
    vendorProofStatus: "NOT_UPLOADED",
    needsDataVerification: true,
    variants: [
      {
        sku: "VEO4-25K-WTY-001",
        variantName: "25K Credits · Warranty",
        durationValue: 30,
        durationUnit: "DAY",
        supplierCostUsdMinor: 0,
        seedVisibleQuantity: null,
        manualSellingPriceNprMinor: 229900,
        purchasable: false,
      },
    ],
  },
  {
    name: "Antigravity Ultra",
    slug: "antigravity-ultra",
    brandSlug: "cursor",
    categorySlug: "developer-tools",
    sourceListingText: "Antigravity Ultra",
    shortDescription: "Availability under review pending authorization confirmation.",
    productType: "DIGITAL_LICENSE",
    fulfillmentType: "MANUAL_CUSTOMER_EMAIL_ACTIVATION",
    productStatus: "DRAFT",
    complianceStatus: "DOCUMENTS_REQUIRED",
    supplyAuthorizationType: "UNKNOWN",
    vendorProofStatus: "NOT_UPLOADED",
    needsDataVerification: true,
    variants: [
      {
        sku: "ANTI-ULTRA-001",
        variantName: "Ultra",
        durationValue: 1,
        durationUnit: "MONTH",
        supplierCostUsdMinor: 0,
        seedVisibleQuantity: null,
        manualSellingPriceNprMinor: 1719900,
        purchasable: false,
      },
    ],
  },
];

/** Additional stock packages from owner inventory (USDT cost → 30% margin). */
export const SEED_STOCK_EXPANSION: SeedProduct[] = [
  {
    name: "Office 365 + 100GB OneDrive — Lifetime",
    slug: "office365-100gb-lifetime",
    brandSlug: "microsoft",
    categorySlug: "productivity",
    sourceListingText: "Office365 + 100GB OneDrive lifetime 0.7 USDT",
    shortDescription: "Microsoft Office apps with 100GB OneDrive — lifetime plan as supplied.",
    productType: "DIGITAL_LICENSE",
    fulfillmentType: "MANUAL_CUSTOMER_EMAIL_ACTIVATION",
    productStatus: "PUBLIC",
    complianceStatus: "APPROVED",
    supplyAuthorizationType: "UNKNOWN",
    vendorProofStatus: "NOT_UPLOADED",
    needsDataVerification: false,
    featured: true,
    variants: [
      {
        sku: "MS-O365-100GB-LT-001",
        variantName: "Lifetime · 100GB",
        durationValue: 1,
        durationUnit: "ONE_TIME",
        supplierCostUsdMinor: usdtToUsdMinor(0.7),
        seedVisibleQuantity: 8,
        manualSellingPriceNprMinor: Math.round(sellNprFromUsdt(0.7) * 100),
        purchasable: true,
      },
    ],
  },
  {
    name: "Office 365 + 1TB OneDrive — Lifetime",
    slug: "office365-1tb-lifetime",
    brandSlug: "microsoft",
    categorySlug: "productivity",
    sourceListingText: "Office365 + 1TB OneDrive lifetime 1 USDT",
    shortDescription: "Microsoft Office apps with 1TB OneDrive — lifetime plan as supplied.",
    productType: "DIGITAL_LICENSE",
    fulfillmentType: "MANUAL_CUSTOMER_EMAIL_ACTIVATION",
    productStatus: "PUBLIC",
    complianceStatus: "APPROVED",
    supplyAuthorizationType: "UNKNOWN",
    vendorProofStatus: "NOT_UPLOADED",
    needsDataVerification: false,
    featured: true,
    variants: [
      {
        sku: "MS-O365-1TB-LT-001",
        variantName: "Lifetime · 1TB",
        durationValue: 1,
        durationUnit: "ONE_TIME",
        supplierCostUsdMinor: usdtToUsdMinor(1),
        seedVisibleQuantity: 1,
        manualSellingPriceNprMinor: Math.round(sellNprFromUsdt(1) * 100),
        purchasable: true,
      },
    ],
  },
  {
    name: "Grammarly Pro — 1 Year",
    slug: "grammarly-pro-1-year",
    brandSlug: "grammarly",
    categorySlug: "productivity",
    sourceListingText: "Grammarly Pro 1 year 7 USDT",
    shortDescription: "Grammarly Pro writing assistant — one year.",
    productType: "DIGITAL_LICENSE",
    fulfillmentType: "MANUAL_CUSTOMER_EMAIL_ACTIVATION",
    productStatus: "PUBLIC",
    complianceStatus: "APPROVED",
    supplyAuthorizationType: "UNKNOWN",
    vendorProofStatus: "NOT_UPLOADED",
    needsDataVerification: false,
    featured: true,
    variants: [
      {
        sku: "GRM-PRO-1Y-001",
        variantName: "1 Year",
        durationValue: 1,
        durationUnit: "YEAR",
        supplierCostUsdMinor: usdtToUsdMinor(7),
        seedVisibleQuantity: null,
        manualSellingPriceNprMinor: Math.round(sellNprFromUsdt(7) * 100),
        purchasable: true,
      },
    ],
  },
  {
    name: "Microsoft 365 Family — 10 Months",
    slug: "microsoft-365-family-10-months",
    brandSlug: "microsoft",
    categorySlug: "productivity",
    sourceListingText: "Microsoft 365 Family 10 months 7 USDT",
    shortDescription: "Microsoft 365 Family plan — 10 months.",
    productType: "DIGITAL_LICENSE",
    fulfillmentType: "MANUAL_CUSTOMER_EMAIL_ACTIVATION",
    productStatus: "PUBLIC",
    complianceStatus: "APPROVED",
    supplyAuthorizationType: "UNKNOWN",
    vendorProofStatus: "NOT_UPLOADED",
    needsDataVerification: false,
    featured: true,
    variants: [
      {
        sku: "MS-365-FAM-10M-001",
        variantName: "Family · 10 Months",
        durationValue: 10,
        durationUnit: "MONTH",
        supplierCostUsdMinor: usdtToUsdMinor(7),
        seedVisibleQuantity: null,
        manualSellingPriceNprMinor: Math.round(sellNprFromUsdt(7) * 100),
        purchasable: true,
      },
    ],
  },
  {
    name: "NordVPN Shared — 3 Months",
    slug: "nordvpn-shared-3-months",
    brandSlug: "nordvpn",
    categorySlug: "productivity",
    sourceListingText: "NordVPN shared 3 months 1 USDT",
    shortDescription: "NordVPN shared access — 3 months.",
    productType: "DIGITAL_LICENSE",
    fulfillmentType: "MANUAL_CUSTOMER_EMAIL_ACTIVATION",
    productStatus: "PUBLIC",
    complianceStatus: "APPROVED",
    supplyAuthorizationType: "UNKNOWN",
    vendorProofStatus: "NOT_UPLOADED",
    needsDataVerification: false,
    variants: [
      {
        sku: "NORD-SHR-3M-001",
        variantName: "Shared · 3 Months",
        durationValue: 3,
        durationUnit: "MONTH",
        supplierCostUsdMinor: usdtToUsdMinor(1),
        seedVisibleQuantity: 7,
        manualSellingPriceNprMinor: Math.round(sellNprFromUsdt(1) * 100),
        purchasable: true,
      },
    ],
  },
  {
    name: "NordVPN on Mail — 3 Months",
    slug: "nordvpn-mail-3-months",
    brandSlug: "nordvpn",
    categorySlug: "productivity",
    sourceListingText: "NordVPN on mail 3 months 3 USDT",
    shortDescription: "NordVPN delivered to your email — 3 months.",
    productType: "DIGITAL_LICENSE",
    fulfillmentType: "MANUAL_CUSTOMER_EMAIL_ACTIVATION",
    productStatus: "PUBLIC",
    complianceStatus: "APPROVED",
    supplyAuthorizationType: "UNKNOWN",
    vendorProofStatus: "NOT_UPLOADED",
    needsDataVerification: false,
    variants: [
      {
        sku: "NORD-MAIL-3M-001",
        variantName: "On Mail · 3 Months",
        durationValue: 3,
        durationUnit: "MONTH",
        supplierCostUsdMinor: usdtToUsdMinor(3),
        seedVisibleQuantity: 8,
        manualSellingPriceNprMinor: Math.round(sellNprFromUsdt(3) * 100),
        purchasable: true,
      },
    ],
  },
  {
    name: "YouTube Premium — 1 Year",
    slug: "youtube-premium-1-year",
    brandSlug: "youtube",
    categorySlug: "video-editing",
    sourceListingText: "YouTube Premium 1 year 25 USDT",
    shortDescription: "YouTube Premium — one year.",
    productType: "DIGITAL_LICENSE",
    fulfillmentType: "MANUAL_CUSTOMER_EMAIL_ACTIVATION",
    productStatus: "PUBLIC",
    complianceStatus: "APPROVED",
    supplyAuthorizationType: "UNKNOWN",
    vendorProofStatus: "NOT_UPLOADED",
    needsDataVerification: false,
    featured: true,
    variants: [
      {
        sku: "YT-PREM-1Y-001",
        variantName: "1 Year",
        durationValue: 1,
        durationUnit: "YEAR",
        supplierCostUsdMinor: usdtToUsdMinor(25),
        seedVisibleQuantity: null,
        manualSellingPriceNprMinor: Math.round(sellNprFromUsdt(25) * 100),
        purchasable: true,
      },
    ],
  },
  {
    name: "Figma Edu — 2 Years",
    slug: "figma-edu-2-years",
    brandSlug: "figma",
    categorySlug: "design",
    sourceListingText: "Figma Edu 2 years 6 USDT",
    shortDescription: "Education eligibility must be verified before sale.",
    productType: "DIGITAL_LICENSE",
    fulfillmentType: "MANUAL_CUSTOMER_EMAIL_ACTIVATION",
    productStatus: "DRAFT",
    complianceStatus: "DOCUMENTS_REQUIRED",
    supplyAuthorizationType: "UNKNOWN",
    vendorProofStatus: "NOT_UPLOADED",
    needsDataVerification: true,
    variants: [
      {
        sku: "FIG-EDU-2Y-001",
        variantName: "Edu · 2 Years",
        durationValue: 2,
        durationUnit: "YEAR",
        supplierCostUsdMinor: usdtToUsdMinor(6),
        seedVisibleQuantity: null,
        manualSellingPriceNprMinor: Math.round(sellNprFromUsdt(6) * 100),
        purchasable: false,
      },
    ],
  },
  {
    name: "Claude Pro — 1 Month",
    slug: "claude-pro-1-month",
    brandSlug: "claude",
    categorySlug: "ai-tools",
    sourceListingText: "Claude Pro 1 month 14 USDT",
    shortDescription: "Availability under review pending authorization confirmation.",
    productType: "DIGITAL_LICENSE",
    fulfillmentType: "MANUAL_CUSTOMER_EMAIL_ACTIVATION",
    productStatus: "DRAFT",
    complianceStatus: "DOCUMENTS_REQUIRED",
    supplyAuthorizationType: "UNKNOWN",
    vendorProofStatus: "NOT_UPLOADED",
    needsDataVerification: true,
    variants: [
      {
        sku: "CLD-PRO-1M-001",
        variantName: "Pro · 1 Month",
        durationValue: 1,
        durationUnit: "MONTH",
        supplierCostUsdMinor: usdtToUsdMinor(14),
        seedVisibleQuantity: null,
        manualSellingPriceNprMinor: Math.round(sellNprFromUsdt(14) * 100),
        purchasable: false,
      },
    ],
  },
  {
    name: "ElevenLabs — 1 Month",
    slug: "elevenlabs-1-month",
    brandSlug: "elevenlabs",
    categorySlug: "ai-tools",
    sourceListingText: "ElevenLabs 1 month NW 7 USDT",
    shortDescription: "Availability under review pending authorization confirmation.",
    productType: "DIGITAL_LICENSE",
    fulfillmentType: "MANUAL_CUSTOMER_EMAIL_ACTIVATION",
    productStatus: "DRAFT",
    complianceStatus: "DOCUMENTS_REQUIRED",
    supplyAuthorizationType: "UNKNOWN",
    vendorProofStatus: "NOT_UPLOADED",
    needsDataVerification: true,
    variants: [
      {
        sku: "ELV-1M-001",
        variantName: "1 Month",
        durationValue: 1,
        durationUnit: "MONTH",
        supplierCostUsdMinor: usdtToUsdMinor(7),
        seedVisibleQuantity: null,
        manualSellingPriceNprMinor: Math.round(sellNprFromUsdt(7) * 100),
        purchasable: false,
      },
    ],
  },
  {
    name: "Notion Business — 3 Months",
    slug: "notion-business-3-months",
    brandSlug: "notion",
    categorySlug: "productivity",
    sourceListingText: "Notion Business 3 month link 2 USDT",
    shortDescription: "Notion Business link package — under review.",
    productType: "DIGITAL_LICENSE",
    fulfillmentType: "MANUAL_CUSTOMER_EMAIL_ACTIVATION",
    productStatus: "DRAFT",
    complianceStatus: "DOCUMENTS_REQUIRED",
    supplyAuthorizationType: "UNKNOWN",
    vendorProofStatus: "NOT_UPLOADED",
    needsDataVerification: true,
    variants: [
      {
        sku: "NOTION-BUS-3M-001",
        variantName: "Business · 3 Months",
        durationValue: 3,
        durationUnit: "MONTH",
        supplierCostUsdMinor: usdtToUsdMinor(2),
        seedVisibleQuantity: 1,
        manualSellingPriceNprMinor: 41900,
        purchasable: false,
      },
    ],
  },
  {
    name: "Cursor Pro — 1 Month",
    slug: "cursor-pro-1-month",
    brandSlug: "cursor",
    categorySlug: "developer-tools",
    sourceListingText: "Cursor Pro 1 month 12 USDT",
    shortDescription: "Cursor does not authorize third-party subscription resellers.",
    productType: "DIGITAL_LICENSE",
    fulfillmentType: "MANUAL_CUSTOMER_EMAIL_ACTIVATION",
    productStatus: "BLOCKED",
    complianceStatus: "REJECTED",
    supplyAuthorizationType: "UNKNOWN",
    vendorProofStatus: "NOT_UPLOADED",
    blockedReason: "Cursor does not authorize third-party subscription resellers.",
    needsDataVerification: false,
    variants: [
      {
        sku: "CUR-PRO-1M-001",
        variantName: "Pro · 1 Month",
        durationValue: 1,
        durationUnit: "MONTH",
        supplierCostUsdMinor: usdtToUsdMinor(12),
        seedVisibleQuantity: null,
        manualSellingPriceNprMinor: Math.round(sellNprFromUsdt(12) * 100),
        purchasable: false,
      },
    ],
  },
];

function withOwnerOverrides(products: SeedProduct[]): SeedProduct[] {
  const archive = new Set<string>(OWNER_ARCHIVE_SLUGS);
  const bySlug = new Map(
    products.filter((p) => !archive.has(p.slug)).map((p) => [p.slug, p]),
  );
  for (const o of [...OWNER_AVAILABLE, ...OWNER_UNDER_REVIEW]) {
    if (archive.has(o.slug)) continue;
    const existing = bySlug.get(o.slug);
    if (existing) bySlug.set(o.slug, applyOverride(existing, o));
  }
  for (const slug of OWNER_BLOCKED_SLUGS) {
    const p = bySlug.get(slug);
    if (!p) continue;
    bySlug.set(slug, {
      ...p,
      productStatus: "BLOCKED",
      complianceStatus: "REJECTED",
      needsDataVerification: false,
      variants: p.variants.map((v) => ({ ...v, purchasable: false })),
    });
  }
  return Array.from(bySlug.values());
}

export const ALL_SEED_PRODUCTS = withOwnerOverrides([
  ...SEED_SCREENSHOT_PRODUCTS,
  ...SEED_OWNED_PRODUCTS,
  ...SEED_NEW_OWNER_PRODUCTS,
  ...SEED_STOCK_EXPANSION,
]);
