import path from "path";
import { renderPoster } from "./generate-all-luxury-posters";

const ROOT = path.join(process.cwd(), "public", "media", "covers");
const WA = "+977 9702910130";

const PRODUCTS = [
  {
    slug: "chatgpt-plus",
    destPath: path.join(ROOT, "chatgpt", "chatgpt-plus.webp"),
    badge: "AI ASSISTANT",
    brandName: "OpenAI",
    productTitle: "ChatGPT Plus",
    tagline: "Smarter AI for a Brighter You",
    accentA: "#10a37f",
    accentB: "#1a7f64",
    bgColorA: "#0a1a14",
    bgColorB: "#051210",
    features: ["GPT-4o & Latest Models", "Advanced Reasoning", "Code, Analyze, Create", "Priority Access & Support"],
    pricingTiers: [
      { label: "1 MONTH", price: "1,050" },
      { label: "3 MONTHS", price: "2,899" },
      { label: "6 MONTHS", price: "5,499" },
      { label: "12 MONTHS", price: "9,999" },
    ],
    logoSvg: `<rect width="180" height="180" rx="36" fill="#10a37f" opacity="0.2"/><text x="90" y="130" text-anchor="middle" font-size="100" font-family="serif" fill="#10a37f" font-weight="900">C</text>`,
    whatsapp: WA,
    rating: "4.8",
    category: "ai-tools",
  },
  {
    slug: "claude-pro",
    destPath: path.join(ROOT, "claude", "claude-pro.webp"),
    badge: "AI ASSISTANT",
    brandName: "Anthropic",
    productTitle: "Claude Pro",
    tagline: "Think Deeper. Create More.",
    accentA: "#d97706",
    accentB: "#b45309",
    bgColorA: "#1a1205",
    bgColorB: "#120d03",
    features: ["Claude 3.5 & Latest", "Long Context Window", "Better Analysis & Coding", "Research & Writing"],
    pricingTiers: [
      { label: "1 MONTH", price: "1,499" },
      { label: "3 MONTHS", price: "2,999" },
      { label: "6 MONTHS", price: "5,499" },
      { label: "12 MONTHS", price: "9,999" },
    ],
    logoSvg: `<circle cx="90" cy="90" r="80" fill="#d97706" fill-opacity="0.15" stroke="#d97706" stroke-width="3"/><text x="90" y="116" text-anchor="middle" font-size="80" font-family="sans-serif" fill="#d97706" font-weight="900">&#x2605;</text>`,
    whatsapp: WA,
    rating: "4.8",
    category: "ai-tools",
  },
  {
    slug: "gemini-pro-18-months-link",
    destPath: path.join(ROOT, "gemini", "gemini-pro.webp"),
    badge: "GOOGLE AI",
    brandName: "Google",
    productTitle: "Gemini AI Pro",
    tagline: "Your AI Creative Partner",
    accentA: "#4285f4",
    accentB: "#7c3aed",
    bgColorA: "#050d1f",
    bgColorB: "#0a0518",
    features: ["Gemini 1.5/2.0 Advanced", "2TB Google Storage", "Gmail, Docs, Slides AI", "AI Studio & NotebookLM"],
    pricingTiers: [
      { label: "NO WARRANTY", price: "399" },
      { label: "6M WARRANTY", price: "1,299" },
      { label: "1Y WARRANTY", price: "2,699" },
    ],
    logoSvg: `<circle cx="90" cy="90" r="80" fill="#4285f4" fill-opacity="0.12"/><text x="90" y="120" text-anchor="middle" font-size="90" font-family="sans-serif" fill="#4285f4" font-weight="900">G</text>`,
    whatsapp: WA,
    rating: "4.8",
    category: "ai-tools",
  },
  {
    slug: "cursor-pro-12m",
    destPath: path.join(ROOT, "cursor", "cursor-pro.webp"),
    badge: "DEVELOPER TOOL",
    brandName: "Anysphere",
    productTitle: "Cursor Pro",
    tagline: "The AI Code Editor",
    accentA: "#a855f7",
    accentB: "#7c3aed",
    bgColorA: "#0d0518",
    bgColorB: "#080310",
    features: ["AI Pair Programming", "Codebase Understanding", "Multi-File Editing", "Built for Developers"],
    pricingTiers: [
      { label: "1 MONTH", price: "1,999" },
      { label: "3 MONTHS", price: "4,999" },
      { label: "6 MONTHS", price: "8,999" },
      { label: "12 MONTHS", price: "15,999" },
    ],
    logoSvg: `<rect width="180" height="180" rx="36" fill="#a855f7" fill-opacity="0.15"/><text x="90" y="128" text-anchor="middle" font-size="90" font-family="monospace" fill="#a855f7" font-weight="900">&#9607;</text>`,
    whatsapp: WA,
    rating: "4.8",
    category: "developer-tools",
  },
  {
    slug: "capcut-pro",
    destPath: path.join(ROOT, "capcut", "capcut-pro.webp"),
    badge: "VIDEO EDITING",
    brandName: "ByteDance",
    productTitle: "CapCut Pro",
    tagline: "Create. Edit. Publish.",
    accentA: "#f43f5e",
    accentB: "#be123c",
    bgColorA: "#1a050a",
    bgColorB: "#100308",
    features: ["4K 60FPS Export", "Auto Captions & AI", "1000+ Templates", "Multi-platform Access"],
    pricingTiers: [
      { label: "7 DAYS", price: "299" },
      { label: "1 MONTH", price: "799" },
      { label: "3 MONTHS", price: "2,399" },
      { label: "6 MONTHS", price: "3,699" },
    ],
    logoSvg: `<rect width="180" height="180" rx="36" fill="#f43f5e" fill-opacity="0.15"/><text x="90" y="128" text-anchor="middle" font-size="90" font-family="sans-serif" fill="#f43f5e" font-weight="900">&#9654;</text>`,
    whatsapp: WA,
    rating: "4.8",
    category: "video-editing",
  },
  {
    slug: "elevenlabs-creator-shared",
    destPath: path.join(ROOT, "elevenlabs", "elevenlabs-creator.webp"),
    badge: "AI AUDIO",
    brandName: "ElevenLabs",
    productTitle: "ElevenLabs",
    tagline: "Voice AI for a New Era",
    accentA: "#6366f1",
    accentB: "#4f46e5",
    bgColorA: "#080a1a",
    bgColorB: "#050712",
    features: ["Realistic AI Voices", "Multiple Languages", "Voice Cloning", "For Creators & Businesses"],
    pricingTiers: [
      { label: "2 MONTHS", price: "2,699" },
      { label: "3 MONTHS", price: "3,699" },
      { label: "6 MONTHS", price: "5,999" },
      { label: "9 MONTHS", price: "7,999" },
    ],
    logoSvg: `<rect width="180" height="180" rx="36" fill="#6366f1" fill-opacity="0.15"/><text x="90" y="128" text-anchor="middle" font-size="90" font-family="sans-serif" fill="#6366f1" font-weight="900">II</text>`,
    whatsapp: WA,
    rating: "4.8",
    category: "ai-tools",
  },
  {
    slug: "higgsfield-pro-12m",
    destPath: path.join(ROOT, "video", "higgsfield-pro.webp"),
    badge: "AI VIDEO",
    brandName: "Higgsfield",
    productTitle: "Higgsfield",
    tagline: "Pro Cinema AI Video",
    accentA: "#ec4899",
    accentB: "#9333ea",
    bgColorA: "#18040f",
    bgColorB: "#0f0318",
    features: ["Cinematic AI Video Gen", "High Quality Outputs", "Multiple Style Control", "Commercial Usage"],
    pricingTiers: [
      { label: "1 MONTH", price: "2,999" },
      { label: "3 MONTHS", price: "6,999" },
      { label: "6 MONTHS", price: "11,999" },
      { label: "12 MONTHS", price: "17,999" },
    ],
    logoSvg: `<rect width="180" height="180" rx="36" fill="#ec4899" fill-opacity="0.15"/><text x="90" y="128" text-anchor="middle" font-size="90" font-family="sans-serif" fill="#ec4899" font-weight="900">H</text>`,
    whatsapp: WA,
    rating: "4.7",
    category: "video-editing",
  },
  {
    slug: "manus-ai-pro-12m",
    destPath: path.join(ROOT, "manus", "manus-ai-pro.webp"),
    badge: "AI AGENT",
    brandName: "Monica AI",
    productTitle: "Manus AI Pro",
    tagline: "Autonomous AI Agent",
    accentA: "#14b8a6",
    accentB: "#0d9488",
    bgColorA: "#021414",
    bgColorB: "#010e0e",
    features: ["Autonomous AI Tasks", "Multi-step Workflows", "Web & File Access", "Advanced Reasoning"],
    pricingTiers: [
      { label: "1 MONTH", price: "1,899" },
      { label: "3 MONTHS", price: "3,999" },
      { label: "6 MONTHS", price: "6,499" },
      { label: "12 MONTHS", price: "9,679" },
    ],
    logoSvg: `<rect width="180" height="180" rx="36" fill="#14b8a6" fill-opacity="0.15"/><text x="90" y="128" text-anchor="middle" font-size="90" font-family="sans-serif" fill="#14b8a6" font-weight="900">M</text>`,
    whatsapp: WA,
    rating: "4.7",
    category: "ai-tools",
  },
  {
    slug: "warp-build-1-year",
    destPath: path.join(ROOT, "developer", "warp-build.webp"),
    badge: "DEVELOPER TOOL",
    brandName: "Warp",
    productTitle: "Warp Build",
    tagline: "Up to 20x Faster Builds",
    accentA: "#0ea5e9",
    accentB: "#0369a1",
    bgColorA: "#020d14",
    bgColorB: "#010a10",
    features: ["20x Faster CI/CD", "Smart Caching", "Team Collaboration", "All Languages & Frameworks"],
    pricingTiers: [
      { label: "1 MONTH", price: "999" },
      { label: "3 MONTHS", price: "1,799" },
      { label: "6 MONTHS", price: "2,699" },
      { label: "1 YEAR", price: "3,699" },
    ],
    logoSvg: `<rect width="180" height="180" rx="36" fill="#0ea5e9" fill-opacity="0.15"/><text x="90" y="128" text-anchor="middle" font-size="90" font-family="sans-serif" fill="#0ea5e9" font-weight="900">W</text>`,
    whatsapp: WA,
    rating: "4.8",
    category: "developer-tools",
  },
  {
    slug: "n8n-starter-1-year",
    destPath: path.join(ROOT, "automation", "n8n-starter.webp"),
    badge: "AUTOMATION",
    brandName: "n8n",
    productTitle: "n8n Starter",
    tagline: "Automate Everything",
    accentA: "#ef4444",
    accentB: "#dc2626",
    bgColorA: "#180505",
    bgColorB: "#100303",
    features: ["500+ Integrations", "Visual Workflow Builder", "Cloud & Self-hosted", "AI Node Support"],
    pricingTiers: [
      { label: "1 MONTH", price: "1,199" },
      { label: "3 MONTHS", price: "2,199" },
      { label: "6 MONTHS", price: "3,299" },
      { label: "1 YEAR", price: "4,699" },
    ],
    logoSvg: `<rect width="180" height="180" rx="36" fill="#ef4444" fill-opacity="0.15"/><text x="90" y="128" text-anchor="middle" font-size="90" font-family="sans-serif" fill="#ef4444" font-weight="900">n</text>`,
    whatsapp: WA,
    rating: "4.7",
    category: "automation",
  },
  {
    slug: "gamma-pro-1-year",
    destPath: path.join(ROOT, "gamma", "gamma-pro.webp"),
    badge: "PRODUCTIVITY",
    brandName: "Gamma App",
    productTitle: "Gamma Pro",
    tagline: "Beautiful Presentations with AI",
    accentA: "#f59e0b",
    accentB: "#d97706",
    bgColorA: "#1a1002",
    bgColorB: "#100a01",
    features: ["AI Slide Generation", "Professional Templates", "Real-time Collaboration", "Custom Branding"],
    pricingTiers: [
      { label: "1 MONTH", price: "1,299" },
      { label: "3 MONTHS", price: "2,499" },
      { label: "6 MONTHS", price: "4,199" },
      { label: "1 YEAR", price: "6,999" },
    ],
    logoSvg: `<rect width="180" height="180" rx="36" fill="#f59e0b" fill-opacity="0.15"/><text x="90" y="128" text-anchor="middle" font-size="90" font-family="sans-serif" fill="#f59e0b" font-weight="900">&#947;</text>`,
    whatsapp: WA,
    rating: "4.8",
    category: "productivity",
  },
  {
    slug: "lovable-pro-12m",
    destPath: path.join(ROOT, "developer", "lovable-pro.webp"),
    badge: "AI DEVELOPER",
    brandName: "Lovable",
    productTitle: "Lovable Pro",
    tagline: "Build Apps with AI",
    accentA: "#fb7185",
    accentB: "#f43f5e",
    bgColorA: "#1a060a",
    bgColorB: "#100408",
    features: ["Full-stack App Builder", "AI Code Generation", "Deploy in Seconds", "Team Collaboration"],
    pricingTiers: [
      { label: "1 MONTH", price: "1,499" },
      { label: "3 MONTHS", price: "2,899" },
      { label: "6 MONTHS", price: "4,699" },
      { label: "12 MONTHS", price: "6,999" },
    ],
    logoSvg: `<rect width="180" height="180" rx="36" fill="#fb7185" fill-opacity="0.15"/><text x="90" y="128" text-anchor="middle" font-size="90" font-family="sans-serif" fill="#fb7185" font-weight="900">L</text>`,
    whatsapp: WA,
    rating: "4.7",
    category: "developer-tools",
  },
  {
    slug: "supabase-pro-1-year",
    destPath: path.join(ROOT, "developer", "supabase-pro.webp"),
    badge: "DEVELOPER TOOL",
    brandName: "Supabase",
    productTitle: "Supabase Pro",
    tagline: "Build Without Limits",
    accentA: "#3ecf8e",
    accentB: "#059669",
    bgColorA: "#021410",
    bgColorB: "#010e0a",
    features: ["Postgres Database", "Auth & Storage", "Edge Functions", "Real-time Capabilities"],
    pricingTiers: [
      { label: "1 MONTH", price: "1,499" },
      { label: "3 MONTHS", price: "2,999" },
      { label: "6 MONTHS", price: "4,699" },
      { label: "1 YEAR", price: "6,999" },
    ],
    logoSvg: `<rect width="180" height="180" rx="36" fill="#3ecf8e" fill-opacity="0.15"/><text x="90" y="128" text-anchor="middle" font-size="90" font-family="sans-serif" fill="#3ecf8e" font-weight="900">S</text>`,
    whatsapp: WA,
    rating: "4.8",
    category: "developer-tools",
  },
  {
    slug: "runway-pro-12m",
    destPath: path.join(ROOT, "video", "runway-pro.webp"),
    badge: "AI VIDEO",
    brandName: "Runway",
    productTitle: "Runway Gen-3",
    tagline: "Video for the Next Era",
    accentA: "#7c3aed",
    accentB: "#5b21b6",
    bgColorA: "#0d0518",
    bgColorB: "#080310",
    features: ["Gen-3 Alpha Turbo", "Video to Video", "Text to Video 4K", "Professional Editing Tools"],
    pricingTiers: [
      { label: "1 MONTH", price: "2,499" },
      { label: "3 MONTHS", price: "5,499" },
      { label: "6 MONTHS", price: "8,999" },
      { label: "12 MONTHS", price: "14,999" },
    ],
    logoSvg: `<rect width="180" height="180" rx="36" fill="#7c3aed" fill-opacity="0.15"/><text x="90" y="128" text-anchor="middle" font-size="90" font-family="sans-serif" fill="#7c3aed" font-weight="900">R</text>`,
    whatsapp: WA,
    rating: "4.7",
    category: "video-editing",
  },
  {
    slug: "framer-pro-12m",
    destPath: path.join(ROOT, "design", "framer-pro.webp"),
    badge: "DESIGN TOOL",
    brandName: "Framer",
    productTitle: "Framer Pro",
    tagline: "Design & Ship Websites",
    accentA: "#0ea5e9",
    accentB: "#7c3aed",
    bgColorA: "#050d18",
    bgColorB: "#050318",
    features: ["Visual Web Builder", "CMS & Localization", "Custom Code Support", "Team Workspaces"],
    pricingTiers: [
      { label: "1 MONTH", price: "1,499" },
      { label: "3 MONTHS", price: "2,999" },
      { label: "6 MONTHS", price: "4,899" },
      { label: "12 MONTHS", price: "7,499" },
    ],
    logoSvg: `<rect width="180" height="180" rx="36" fill="#0ea5e9" fill-opacity="0.15"/><text x="90" y="128" text-anchor="middle" font-size="90" font-family="sans-serif" fill="#0ea5e9" font-weight="900">F</text>`,
    whatsapp: WA,
    rating: "4.7",
    category: "design",
  },
  {
    slug: "mobbin-12m",
    destPath: path.join(ROOT, "design", "mobbin-pro.webp"),
    badge: "DESIGN TOOL",
    brandName: "Mobbin",
    productTitle: "Mobbin Pro",
    tagline: "World's Best UI References",
    accentA: "#22d3ee",
    accentB: "#0891b2",
    bgColorA: "#021418",
    bgColorB: "#010e10",
    features: ["50,000+ UI Screens", "iOS & Android References", "Web App Designs", "10-Person Team License"],
    pricingTiers: [
      { label: "1 MONTH", price: "1,499" },
      { label: "3 MONTHS", price: "2,799" },
      { label: "6 MONTHS", price: "4,499" },
      { label: "12 MONTHS", price: "6,999" },
    ],
    logoSvg: `<rect width="180" height="180" rx="36" fill="#22d3ee" fill-opacity="0.15"/><text x="90" y="128" text-anchor="middle" font-size="90" font-family="sans-serif" fill="#22d3ee" font-weight="900">M</text>`,
    whatsapp: WA,
    rating: "4.8",
    category: "design",
  },
  {
    slug: "gumloop-pro-12m",
    destPath: path.join(ROOT, "automation", "gumloop-pro.webp"),
    badge: "AUTOMATION",
    brandName: "Gumloop",
    productTitle: "Gumloop Pro",
    tagline: "No-Code AI Automation",
    accentA: "#34d399",
    accentB: "#10b981",
    bgColorA: "#021410",
    bgColorB: "#010e0a",
    features: ["Visual AI Builder", "500+ Integrations", "Web Scraping Built-in", "Unlimited Workflows"],
    pricingTiers: [
      { label: "1 MONTH", price: "999" },
      { label: "3 MONTHS", price: "1,899" },
      { label: "6 MONTHS", price: "2,899" },
      { label: "12 MONTHS", price: "4,499" },
    ],
    logoSvg: `<rect width="180" height="180" rx="36" fill="#34d399" fill-opacity="0.15"/><text x="90" y="128" text-anchor="middle" font-size="90" font-family="sans-serif" fill="#34d399" font-weight="900">G</text>`,
    whatsapp: WA,
    rating: "4.7",
    category: "automation",
  },
  {
    slug: "notion-business-12m",
    destPath: path.join(ROOT, "productivity", "notion-business.webp"),
    badge: "PRODUCTIVITY",
    brandName: "Notion",
    productTitle: "Notion Business",
    tagline: "Organize Everything",
    accentA: "#e2e8f0",
    accentB: "#cbd5e1",
    bgColorA: "#101010",
    bgColorB: "#0a0a0a",
    features: ["Unlimited Blocks", "Team Collaboration", "Larger File Uploads", "Integrations & Automation"],
    pricingTiers: [
      { label: "1 MONTH", price: "1,099" },
      { label: "3 MONTHS", price: "2,199" },
      { label: "6 MONTHS", price: "3,499" },
      { label: "12 MONTHS", price: "4,999" },
    ],
    logoSvg: `<rect width="180" height="180" rx="36" fill="#e2e8f0" fill-opacity="0.12"/><text x="90" y="128" text-anchor="middle" font-size="90" font-family="sans-serif" fill="#e2e8f0" font-weight="900">N</text>`,
    whatsapp: WA,
    rating: "4.8",
    category: "productivity",
  },
  {
    slug: "granola-business-12m",
    destPath: path.join(ROOT, "productivity", "granola-business.webp"),
    badge: "PRODUCTIVITY",
    brandName: "Granola",
    productTitle: "Granola AI",
    tagline: "AI Meeting Notes, Supercharged",
    accentA: "#fb923c",
    accentB: "#ea580c",
    bgColorA: "#1a0c04",
    bgColorB: "#100803",
    features: ["AI Meeting Notes", "Auto-Transcription", "Action Items Detection", "Team Sharing"],
    pricingTiers: [
      { label: "1 MONTH", price: "1,299" },
      { label: "3 MONTHS", price: "2,499" },
      { label: "6 MONTHS", price: "3,999" },
      { label: "12 MONTHS", price: "5,999" },
    ],
    logoSvg: `<rect width="180" height="180" rx="36" fill="#fb923c" fill-opacity="0.15"/><text x="90" y="128" text-anchor="middle" font-size="90" font-family="sans-serif" fill="#fb923c" font-weight="900">G</text>`,
    whatsapp: WA,
    rating: "4.7",
    category: "productivity",
  },
  {
    slug: "railway-hobby-12m",
    destPath: path.join(ROOT, "developer", "railway-hobby.webp"),
    badge: "CLOUD DEPLOY",
    brandName: "Railway",
    productTitle: "Railway Hobby",
    tagline: "Deploy Without Limits",
    accentA: "#8b5cf6",
    accentB: "#6d28d9",
    bgColorA: "#0c0518",
    bgColorB: "#080310",
    features: ["Higher Build Limits", "Custom Domains", "Analytics & Monitoring", "For Serious Builders"],
    pricingTiers: [
      { label: "1 MONTH", price: "999" },
      { label: "3 MONTHS", price: "1,899" },
      { label: "6 MONTHS", price: "2,899" },
      { label: "12 MONTHS", price: "3,999" },
    ],
    logoSvg: `<rect width="180" height="180" rx="36" fill="#8b5cf6" fill-opacity="0.15"/><text x="90" y="128" text-anchor="middle" font-size="90" font-family="sans-serif" fill="#8b5cf6" font-weight="900">&#128659;</text>`,
    whatsapp: WA,
    rating: "4.7",
    category: "developer-tools",
  },
  {
    slug: "factory-12m",
    destPath: path.join(ROOT, "developer", "factory-droid.webp"),
    badge: "AI CODING",
    brandName: "Factory",
    productTitle: "Factory Droid",
    tagline: "AI for Enterprise Engineering",
    accentA: "#64748b",
    accentB: "#475569",
    bgColorA: "#0d1018",
    bgColorB: "#080a10",
    features: ["Autonomous Code Droids", "Large Codebase Support", "Multi-language Support", "Team Collaboration"],
    pricingTiers: [
      { label: "1 MONTH", price: "1,699" },
      { label: "3 MONTHS", price: "3,499" },
      { label: "6 MONTHS", price: "5,499" },
      { label: "12 MONTHS", price: "8,999" },
    ],
    logoSvg: `<rect width="180" height="180" rx="36" fill="#64748b" fill-opacity="0.15"/><text x="90" y="128" text-anchor="middle" font-size="90" font-family="sans-serif" fill="#94a3b8" font-weight="900">&#9874;</text>`,
    whatsapp: WA,
    rating: "4.6",
    category: "developer-tools",
  },
  {
    slug: "supergrok-3-months",
    destPath: path.join(ROOT, "grok", "supergrok.webp"),
    badge: "AI ASSISTANT",
    brandName: "xAI",
    productTitle: "SuperGrok",
    tagline: "Real-time X/Twitter Intelligence",
    accentA: "#f9fafb",
    accentB: "#e5e7eb",
    bgColorA: "#121214",
    bgColorB: "#0a0a0c",
    features: ["Grok 2 & Vision Models", "Real-time X Data Access", "Deep Research Mode", "Unlimited Usage"],
    pricingTiers: [
      { label: "1 MONTH", price: "1,299" },
      { label: "3 MONTHS", price: "2,499" },
    ],
    logoSvg: `<rect width="180" height="180" rx="36" fill="#f9fafb" fill-opacity="0.08"/><text x="90" y="128" text-anchor="middle" font-size="90" font-family="sans-serif" fill="#f9fafb" font-weight="900">X</text>`,
    whatsapp: WA,
    rating: "4.7",
    category: "ai-tools",
  },
  {
    slug: "canva-pro-1-year",
    destPath: path.join(ROOT, "canva", "canva-pro.webp"),
    badge: "DESIGN TOOL",
    brandName: "Canva",
    productTitle: "Canva Pro",
    tagline: "Design Like a Pro",
    accentA: "#00c4cc",
    accentB: "#7d2ae8",
    bgColorA: "#021418",
    bgColorB: "#0c0518",
    features: ["Premium Templates", "Brand Kit & Resize", "Background Remover", "For Teams & Individuals"],
    pricingTiers: [
      { label: "1 YEAR", price: "1,195" },
    ],
    logoSvg: `<rect width="180" height="180" rx="36" fill="#00c4cc" fill-opacity="0.15"/><text x="90" y="128" text-anchor="middle" font-size="90" font-family="sans-serif" fill="#00c4cc" font-weight="900">C</text>`,
    whatsapp: WA,
    rating: "4.9",
    category: "design",
  },
  {
    slug: "coursera-premium-1-year",
    destPath: path.join(ROOT, "coursera", "coursera-premium.webp"),
    badge: "LEARNING",
    brandName: "Coursera",
    productTitle: "Coursera Plus",
    tagline: "7,000+ Courses & Certificates",
    accentA: "#0056d2",
    accentB: "#003d95",
    bgColorA: "#020814",
    bgColorB: "#01050e",
    features: ["7,000+ Courses", "Verified Certificates", "Guided Projects", "Professional Certificates"],
    pricingTiers: [
      { label: "3 MONTHS", price: "1,299" },
      { label: "6 MONTHS", price: "1,899" },
      { label: "1 YEAR", price: "2,499" },
    ],
    logoSvg: `<rect width="180" height="180" rx="36" fill="#0056d2" fill-opacity="0.15"/><text x="90" y="128" text-anchor="middle" font-size="90" font-family="sans-serif" fill="#0056d2" font-weight="900">C+</text>`,
    whatsapp: WA,
    rating: "4.8",
    category: "learning",
  },
  {
    slug: "veo3-ultra-flow-credits",
    destPath: path.join(ROOT, "video", "veo3-ultra.webp"),
    badge: "GOOGLE AI",
    brandName: "Google",
    productTitle: "Veo 3 Ultra",
    tagline: "Next-Gen AI Video Generation",
    accentA: "#4285f4",
    accentB: "#34a853",
    bgColorA: "#050d1a",
    bgColorB: "#020a0e",
    features: ["45,000 Flow Credits", "Veo 3 Video Model", "Photorealistic Output", "Extended Durations"],
    pricingTiers: [
      { label: "1 MONTH", price: "2,999" },
    ],
    logoSvg: `<rect width="180" height="180" rx="36" fill="#4285f4" fill-opacity="0.15"/><text x="90" y="128" text-anchor="middle" font-size="80" font-family="sans-serif" fill="#4285f4" font-weight="900">Veo3</text>`,
    whatsapp: WA,
    rating: "4.8",
    category: "video-editing",
  },
  {
    slug: "kling-standard-680-750-credits",
    destPath: path.join(ROOT, "kling", "kling-standard.webp"),
    badge: "AI VIDEO",
    brandName: "Kling AI",
    productTitle: "Kling Standard",
    tagline: "Cinematic AI Video Creation",
    accentA: "#3b82f6",
    accentB: "#1d4ed8",
    bgColorA: "#020814",
    bgColorB: "#01050e",
    features: ["750 Credits Monthly", "1080p HD Output", "Text & Image to Video", "Multiple Aspect Ratios"],
    pricingTiers: [
      { label: "1 MONTH", price: "1,399" },
    ],
    logoSvg: `<rect width="180" height="180" rx="36" fill="#3b82f6" fill-opacity="0.15"/><text x="90" y="128" text-anchor="middle" font-size="90" font-family="sans-serif" fill="#3b82f6" font-weight="900">K</text>`,
    whatsapp: WA,
    rating: "4.6",
    category: "video-editing",
  },
  {
    slug: "claude-code-api-access",
    destPath: path.join(ROOT, "claude", "claude-code-api.webp"),
    badge: "AI API",
    brandName: "Anthropic",
    productTitle: "Claude API",
    tagline: "Direct API Token Access",
    accentA: "#d97706",
    accentB: "#92400e",
    bgColorA: "#1a1205",
    bgColorB: "#100d03",
    features: ["10M-100M Token Pools", "Claude 3.5 Sonnet", "Code & Terminal Access", "API Direct Integration"],
    pricingTiers: [
      { label: "10M TOKENS", price: "1,299" },
      { label: "50M TOKENS", price: "2,699" },
      { label: "100M 1-DAY", price: "4,699" },
      { label: "100M 7-DAY", price: "7,499" },
    ],
    logoSvg: `<rect width="180" height="180" rx="36" fill="#d97706" fill-opacity="0.12"/><text x="90" y="128" text-anchor="middle" font-size="60" font-family="monospace" fill="#d97706" font-weight="900">&lt;API&gt;</text>`,
    whatsapp: WA,
    rating: "4.8",
    category: "developer-tools",
  },
  {
    slug: "ai-prompt-starter-pack",
    destPath: path.join(ROOT, "ai", "ai-prompt-pack.webp"),
    badge: "DIGITAL ASSET",
    brandName: "TRIHEX",
    productTitle: "Prompt Pack",
    tagline: "500+ Production AI Prompts",
    accentA: "#a855f7",
    accentB: "#7c3aed",
    bgColorA: "#0d0518",
    bgColorB: "#080310",
    features: ["500+ Curated Prompts", "ChatGPT, Claude, Gemini", "Business & Creative", "Instant Digital Delivery"],
    pricingTiers: [
      { label: "ONE-TIME", price: "499" },
    ],
    logoSvg: `<rect width="180" height="180" rx="36" fill="#a855f7" fill-opacity="0.15"/><text x="90" y="128" text-anchor="middle" font-size="90" font-family="sans-serif" fill="#a855f7" font-weight="900">&#128161;</text>`,
    whatsapp: WA,
    rating: "4.8",
    category: "digital-assets",
  },
];

async function main() {
  console.log(`Generating ${PRODUCTS.length} premium product posters...`);
  let success = 0;
  let failed = 0;
  for (const p of PRODUCTS) {
    try {
      await renderPoster({
        ...p,
        category: p.category,
      });
      success++;
    } catch (err) {
      console.error(`FAILED: ${p.slug} — ${err}`);
      failed++;
    }
  }
  console.log(`\nDone! ${success} succeeded, ${failed} failed.`);
}

main().catch(console.error);
